[project]
name = 'clarity-security-templates'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []

[contracts.ownable-trait]
path = 'contracts/ownable-trait.clar'
clarity_version = 3
epoch = 3.0

[contracts.ownable-template]
path = 'contracts/ownable-template.clar'
clarity_version = 3
epoch = 3.0

[contracts.example-dao-treasury]
path = 'contracts/example-dao-treasury.clar'
clarity_version = 3
epoch = 3.0
depends_on = ['ownable-trait']  

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false